const OurList=[
  {
    id:1,
    news:"Why I'm suing the US govet",
    source:"bunnieStudios.com",
    comments:"257 comments",
    points:"1346 points",
    time:"11 hours ago",
  },
  {
    id:2,
    news:"Zenzizenzizenzenzic",
    source:"wikipedia.org",
    comments:"521 comments",
    points:"140 points",
    time:"3 hours ago",
  },
  {
    id:3,
    news:"A practical web developer",
    source:"github.com",
    comments:"72 comments",
    points:"310 points",
    time:"8 hours ago",
  },
  {
    id:4,
    news:"I got arrested and represented myself in court",
    source:"mediium.com",
    comments:"789 comments",
    points:"120 points",
    time:"7 hours ago",
  },
  {
    id:5,
    news:"Sculpture of Housing Prices Ripping San Fransisco Apart",
    source:"dougmoone.com",
    comments:"110 comments",
    points:"110 points",
    time:"1 hours ago",
  },
  {
    id:6,
    news:"practical guide to bare metal",
    source:"gitbooks.io",
    comments:"450 comments",
    points:"70 points",
    time:"2 hours ago",
  },
  {
    id:7,
    news:"Superformula",
    source:"wikipedia.org",
    comments:"17 comments",
    points:"60 points",
    time:"9 hours ago",
  },
  {
    id:8,
    news:"Police asked 3D printing lab to recreate a dead man's fingers to unlock phone",
    source:"fusion.net",
    comments:"24 comments",
    points:"58 points",
    time:"13 hours ago",
  },
  {
    id:9,
    news:"Edward Snowman's new research aims to keep smartphones from betraying owners",
    source:"theintercept.com",
    comments:"24 comments",
    points:"50 points",
    time:"3 hours ago",
  },
  {
    id:10,
    news:"Assessing IBM's POWER8, part 1: A low Level Look at Little Endian",
    source:"ananstech.com",
    comments:"1 comments",
    points:"6 points",
    time:"3 hours ago",
  }
]

export default OurList